### ISSUE TITLE
how do you bootstrap the emacs.d?

### ISSUE THREAD

**Issue by ninrod** [dakrone/eos#1]
Hi @dakrone, 

I'm curious, how do you boostrap the untangled org setup files?

I understand that somewhere on your setup you have to have an init.el or ~/.emacs file that calls org-babel to untangle the org files into `el` files. But I don't see an `init.el` in your configuration. the `Makefile` does not seem to be creating one either.

**Comment by dakrone** [comment]
> I'm curious, how do you boostrap the untangled org setup files?

You should be able to run `make` to generate all of the `.el` files, and then if you want to use the configuration, `make install` will set up symlinks to the generated init.el files (check out `install.sh` which is run by the Makefile and see that it creates the `init.el` symlink)

**Comment by ninrod** [comment]
ok, thank you @dakrone. 

I'm trying to grab some ideas on how to setup emacs for java development, a.k.a, the final frontier. 

I see that you are using meghanada server. Are you liking it? thanks

**Comment by dakrone** [comment]
> I see that you are using meghanada server. Are you liking it? thanks

It works pretty well, I do appreciate that it's better ingrained into Emacs than something like Eclim is, since it hooks into flycheck and company a bit easier. I've had a few issues with the server dying due to NullPointerExceptions but it is getting better (and it's actively developed).
